# @package dataset
name:
  HateSpeech

load:
  train:
    _target_: src.data_preparation.PandasDataset.PandasDataset
    root: ${paths.datasets}/datasets/HateSpeech/labeled_data.csv
    cut: [0, 19000]
    names:
      label:
        class
      text:
        tweet
    add_one: 1

  test:
    _target_: src.data_preparation.PandasDataset.PandasDataset
    root: ${paths.datasets}/datasets/HateSpeech/labeled_data.csv
    cut: [19000, null]
    names:
      label:
        class
      text:
        tweet
    add_one: 1


val_split: 0.8

classes:
  4

