# @package dataset
name:
  imdb

load:
  train:
    _target_: torchtext.datasets.IMDB
    root: ${paths.datasets}
    split: train
  test:
    _target_: torchtext.datasets.IMDB
    root: ${paths.datasets}
    split: test

split:
  _target_: dataset_split
  val_split: 0.2

classes:
  2

