# @package dataset
name:
  yahoo
load_train:
  _target_: torchtext.datasets.YahooAnswers
  root: ${paths.datasets}
  split: train
load_test:
  _target_: torchtext.datasets.YahooAnswers
  root: ${paths.datasets}
  split: test
