defaults:
  - paths
  - logging
  - data_loading
  - trainer: trainer
  - dataset: imdb
  - model: bert
  - tokenizer: bert-tokenizer
  - _self_

hydra:
  mode:
    MULTIRUN
  sweeper:
    params:
      dataset: imdb
#      glob(*)
      model: glob(*)
      tokenizer: glob(*)