defaults:
  - paths
  - logging
  - data_loading
  - trainer: trainer
  - dataset: imdb
  - experiments: bert
#  - model: minilm
#  - tokenizer: minilm-tokenizer
  - _self_

hydra:
  mode:
    MULTIRUN
  sweeper:
    params:
#      dataset: glob(*)
      experiments: glob(*)

version:
  1.1.0