defaults:
  - paths
  - logging
  - data_loading
  - trainer: trainer
  - dataset: welfake
  - experiments: minilm
#  - model: minilm
#  - tokenizer: minilm-tokenizer
  - _self_

hydra:
  mode:
    RUN
  sweeper:
    params:
      dataset: glob(*,exclude=[yahoo,hatespeech])
      experiments: glob(*,exclude=bert)

version:
  1.2.0