defaults:
  - paths
  - logging
  - data_loading
  - trainer: trainer
  - dataset: hatespeech
  - experiments: minilm
#  - model: minilm
#  - tokenizer: minilm-tokenizer
  - _self_

hydra:
  mode:
    MULTIRUN
  sweeper:
    params:
      dataset: hatespeech
      experiments: distilbert, minilm

version:
  1.2.0