defaults:
  - paths
  - logging
  - data_loading
  - trainer: trainer
  - dataset: imdb
  - model: bert
  - tokenizer: bert-tokenizer
  - _self_

hydra:
  mode:
    RUN
  sweeper:
    params:
      dataset: glob(*)
      model: glob(*)
      tokenizer: glob(*)

version:
  1.0.1